# -----------------------------------------------------------------------
# We don't support docker compose for production environments.
# If you choose to use this type of deployment make sure to
# create you own docker environment file (docker/.env) with your own
# unique random secure passwords and SECRET_KEY.
#
# For verbose logging during development:
# - Set SUPERSET_LOG_LEVEL=debug in docker/.env-local for detailed Superset logs
# -----------------------------------------------------------------------
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker # kms: затираем папку из образа локальной папкой!
  - superset_home:/app/superset_home

services:
  db:
    env_file:
      - ../.env           # global
      - .env              # local
      - docker/.env
#      - docker/.env-local
    image: postgres:16
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    profiles: ["fallback-db"]

  superset:
    extra_hosts:
      - "${HOSTNAME}:127.0.0.1"
      - "localhost:127.0.0.1"
    network_mode: host
    env_file:
      - ../.env           # global
      - .env              # local
      - docker/.env
#      - docker/.env-local
    image: assanj/superset-app:latest2025Nov 
    container_name: superset_app
    command: ["/usr/bin/run-server.sh"]
    user: "root"
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes

  superset-init:
    extra_hosts:
      - "${HOSTNAME}:127.0.0.1"
      - "localhost:127.0.0.1"
    network_mode: host
    container_name: superset_init
    image: assanj/superset-app:latest2025Nov
    command: ["/app/docker/docker-init-smart.sh"]
    env_file:
      - ../.env           # global
      - .env              # local
      - docker/.env
#      - docker/.env-local
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-localhost}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USER=${DATABASE_USER:-superset}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-superset}
      - DATABASE_DB=${DATABASE_DB:-superset}
      - POSTGRES_ADMIN_USER=${POSTGRES_ADMIN_USER:-postgres}
      - POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-postgres}
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    extra_hosts:
      - "${HOSTNAME}:127.0.0.1"
      - "localhost:127.0.0.1"
    network_mode: host
    image: assanj/superset-worker:latest2025Nov
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file:
      - ../.env           # global
      - .env              # local
      - docker/.env
#      - docker/.env-local
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"]

  superset-worker-beat:
    extra_hosts:
      - "${HOSTNAME}:127.0.0.1"
      - "localhost:127.0.0.1"
    network_mode: host
    image: assanj/superset-worker-beat:latest2025Nov
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file:
      - ../.env           # global
      - .env              # local
      - docker/.env
#      - docker/.env-local
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  db_home:
    external: false
