services:
  postgres:
    image: postgres:16
    container_name: prod-postgres
    restart: unless-stopped
    env_file:
      - path: ../.env  # Общий файл
        required: false
      - path: docker/.env # default
        required: false
      - path: docker/.env-local # optional override
        required: false
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-md5}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - bi-network

networks:
  bi-network:
    external: false

volumes:
  postgres_data:
    external: false
    name: ${POSTGRES_VOLUME_NAME:-postgres_data}
