services:
  postgres:
    image: postgres:16
    container_name: prod-postgres
    network_mode: host
    restart: unless-stopped
    env_file:
      - path: ../.env  # Общий файл
        required: false
      - path: docker/.env # default
        required: false
      - path: docker/.env-local # optional override
        required: false
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-md5}
    command: >
      postgres
      -c listen_addresses='*'
      -c port=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports: НЕ НУЖНЫ при network_mode: host

volumes:
  postgres_data:
    external: false
    name: ${POSTGRES_VOLUME_NAME:-postgres_data}
